Fix for issue 333
merzlab/QUICK pull request #334
Opened 2024-03-12 02:02 UTC by Madu86

The enclosed changes resolve #333. Please check and merge.

2024-03-13 01:30 UTC, agoetz requested changes
Format specifiers need adjusting to allow larger numbers for coordinates and total energy,

2024-03-13 01:30 UTC, agoetz commented on src/modules/quick_molden_module.f90
> +           write(self%iMoldenFile, '(3(4x,F13.10))') (self%xyz_snapshots(j,i,k),j=1,3)
This looks dangerous. F13.10 has field width 13 and 10 significant digits. Add one for the decimal point and one for  a minus sign, and this leaves only a single digit for the integer part of the coordinate.

I would use '3(2x,F20.10))' as format.

2024-03-13 01:30 UTC, agoetz commented on src/modules/quick_molden_module.f90
> +           write(self%iMoldenFile, '(3(4x,F13.10))') (xyz(j,i),j=1,3)
Same as above suggestion to use '3(2x,F20.10))' format.

2024-03-13 01:30 UTC, agoetz commented on src/modules/quick_molden_module.f90
> +        write(self%iMoldenFile, '("  Ene= ", F15.10)') quick_qm_struct%E(i)
This does not allow for large energies. Use F20.20 or scientific notation.

2024-03-13 01:30 UTC, agoetz commented on src/modules/quick_molden_module.f90
> +            write(self%iMoldenFile, '("  Ene= ",F15.10)') quick_qm_struct%Eb(i)
Same as above, allow larger total energy numbers (use F20.20 or scientific notation).

2024-03-15 01:23 UTC, Madu86 commented
@agoetz, Thanks for pointing these out. I have made changes. Please check.

2024-03-15 19:08 UTC, merged